Update unit tests to use the methods compatible with Python 3.12 (#5398)
# Description

In Python 3.12, the following two methods are fully deprecated and would
lead to unit test failures:

```
assertEquals
assertNotEquals
```

e.g.,

```
ERROR: test_interpolate_clean (tests.data_preparation.models.block.dbt.test_profiles.ProfilesTest.test_interpolate_clean)
Test the Profiles Interface by
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 90, in _callTestMethod
    if self._callMaybeAsync(method) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 117, in _callMaybeAsync
    return self._asyncioTestContext.run(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hw/workspace/dev/mage-ai/mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py", line 88, in test_interpolate_clean
    self.assertNotEquals(
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProfilesTest' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?
```

These two methods have been changed to the equivalent ones, i.e., 

```
assertEqual
assertNotEqual
```

In addition, the following methods are invalid assertions, that lead to
unit test errors in Python 3.12:

```
called_once_with
called_once
not_called
```

which have been updated to valid ones:

```
assert_called_once_with
assert_called_once
assert_not_called
```

# How Has This Been Tested?
<!-- Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
-->

- [X] Tested in a local development environment

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature,
documentation)
- [X] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my
feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

cc:
<!-- Optionally mention someone to let them know about this pull request
-->
@wangxiaoyou1993