[hw] Avoid throwing exceptions when `block_type` is None (#5439)
# Description

When the block_type value is `None`, the following code would throw
exception:

```
>> block_type + 's'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

However, the following code works fine:
```
>> f'{block_type}s'

'Nones'
```

It was showing as “BlockType.###s” earlier for valid block_types, due to
the behavior change of StrEnum in Python 3.11+. It was changed to
`block_type +'s'` to pass existing unit tests. With the later StrEnum
change, this work-around was not needed anymore.

# How Has This Been Tested?
<!-- Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
-->

- [X] Manually tested in a local development environment
```
(.venv) mage-ai % python3 -m unittest mage_ai.tests.data_preparation.models.test_block.BlockTest
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
.[ERROR] Pipeline.get_block: block test_transformer with type None does not exist in pipeline test_pipeline_delete for repo_path /Users/hw/workspace/dev/mage-ai/test.
.[ERROR] Pipeline.get_block: block test_data_loader with type None does not exist in pipeline test_pipeline_delete_force for repo_path /Users/hw/workspace/dev/mage-ai/test.
................
----------------------------------------------------------------------
Ran 18 tests in 1.017s

OK
```

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature,
documentation)
- [X] I have performed a self-review of my own code
- [X] I have added unit tests that prove my fix is effective or that my
feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

cc:
<!-- Optionally mention someone to let them know about this pull request
-->
@wangxiaoyou1993